import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar.js'
import Form from './components/form.js'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Koby Sillito\'s Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
