import './globals.css'
import Navbar from './components/navbar.js'
import Form from './components/form.js'

export const metadata = {
  title: 'Koby Sillito\'s Portfolio',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
    </>
  );
}
